/**
 * Generate CLI registry from src/components/ui/*.tsx
 *
 * Parses each component file to extract:
 * - npm dependencies (@radix-ui/*, recharts)
 * - internal registry dependencies (./field, ./button-group, ./button)
 * - Object.assign namespace pattern detection
 * - file content embedding
 *
 * Base dependencies (clsx, tailwind-merge, class-variance-authority)
 * are installed at `init` time, not per-component.
 *
 * Output: cli/src/registry/index.ts
 */

import fs from 'node:fs'
import path from 'node:path'

const UI_DIR = path.resolve(__dirname, '..', 'src', 'components', 'ui')
const OUTPUT = path.resolve(__dirname, '..', 'cli', 'src', 'registry', 'index.ts')

// Base deps installed at init — skip these in per-component deps
const BASE_DEPS = new Set([
  'class-variance-authority',
  'clsx',
  'tailwind-merge',
  'react',
  'react-dom',
])

// Chart aliases: these all resolve to chart.tsx
const CHART_ALIASES = ['bar-chart', 'line-chart', 'area-chart', 'pie-chart']

// Convenience aliases: shorthand names for common components
const CONVENIENCE_ALIASES: Record<string, string> = {
  'radio': 'radio-group',
  'nav': 'navigation-menu',
  'dropdown-menu': 'dropdown',
}

// field is internal-only — not exposed as CLI command
const INTERNAL_ONLY = new Set(['field'])

// button-group reverse dependency: add button-group → also add button
const REVERSE_DEPS: Record<string, string[]> = {
  'button-group': ['button'],
}

interface ParsedComponent {
  name: string
  dependencies: string[]
  registryDependencies: string[]
  reverseDependencies: string[]
  namespace: boolean
  content: string
  aliases?: string[]
}

function parseComponent(filePath: string): ParsedComponent {
  const name = path.basename(filePath, '.tsx')
  const content = fs.readFileSync(filePath, 'utf-8')

  // Extract npm dependencies (exclude base deps and relative/alias imports)
  const npmDeps = new Set<string>()
  const importRegex = /^import\s+.+\s+from\s+['"]([^.'@/][^'"]*)['"]/gm
  let match: RegExpExecArray | null
  while ((match = importRegex.exec(content)) !== null) {
    const pkg = match[1]
    if (!BASE_DEPS.has(pkg)) {
      npmDeps.add(pkg)
    }
  }

  // Extract scoped packages (@radix-ui/*, @scope/*)
  const scopedRegex = /^import\s+.+\s+from\s+['"](@[^/]+\/[^'"]+)['"]/gm
  while ((match = scopedRegex.exec(content)) !== null) {
    npmDeps.add(match[1])
  }

  // Extract internal registry dependencies (./name and @/components/ui/name imports)
  const registryDeps = new Set<string>()
  const internalRegex = /^import\s+.+\s+from\s+['"]\.\/([^'"]+)['"]/gm
  while ((match = internalRegex.exec(content)) !== null) {
    registryDeps.add(match[1])
  }
  const aliasImportRegex = /^import\s+.+\s+from\s+['"]@\/components\/ui\/([^'"]+)['"]/gm
  while ((match = aliasImportRegex.exec(content)) !== null) {
    const dep = match[1]
    if (dep !== name) registryDeps.add(dep)
  }

  // Detect Object.assign namespace pattern
  const namespace = /Object\.assign\(/.test(content)

  // Reverse dependencies
  const reverseDeps = REVERSE_DEPS[name] || []

  // Chart aliases
  const aliases = name === 'chart' ? CHART_ALIASES : undefined

  return {
    name,
    dependencies: [...npmDeps].sort(),
    registryDependencies: [...registryDeps].sort(),
    reverseDependencies: reverseDeps,
    namespace,
    content,
    aliases,
  }
}

function generateRegistryFile(components: ParsedComponent[]): string {
  const lines: string[] = [
    '// Auto-generated by scripts/generate-registry.ts',
    '// Do NOT edit manually — run: npm run generate:registry',
    '',
    "import type { Registry } from './schema'",
    '',
    'export const registry: Registry = {',
  ]

  for (const comp of components) {
    // Escape backticks and ${} in content for template literal
    const escaped = comp.content
      .replace(/\\/g, '\\\\')
      .replace(/`/g, '\\`')
      .replace(/\$\{/g, '\\${')

    lines.push(`  '${comp.name}': {`)
    lines.push(`    name: '${comp.name}',`)
    lines.push(`    dependencies: ${JSON.stringify(comp.dependencies)},`)
    lines.push(`    registryDependencies: ${JSON.stringify(comp.registryDependencies)},`)
    lines.push(`    reverseDependencies: ${JSON.stringify(comp.reverseDependencies)},`)
    lines.push(`    namespace: ${comp.namespace},`)
    lines.push(`    description: '',`)
    if (comp.aliases) {
      lines.push(`    aliases: ${JSON.stringify(comp.aliases)},`)
    }
    lines.push(`    files: [{`)
    lines.push(`      path: '${comp.name}.tsx',`)
    lines.push(`      content: \`${escaped}\`,`)
    lines.push(`      type: 'ui',`)
    lines.push(`    }],`)
    lines.push(`  },`)
  }

  lines.push('}')
  lines.push('')

  // Component aliases (chart + convenience)
  lines.push('/** Aliases — shorthand or alternate names that resolve to real registry items */')
  lines.push('export const COMPONENT_ALIASES: Record<string, string> = {')
  lines.push('  // Chart aliases')
  for (const alias of CHART_ALIASES) {
    lines.push(`  '${alias}': 'chart',`)
  }
  lines.push('  // Convenience aliases')
  for (const [alias, target] of Object.entries(CONVENIENCE_ALIASES)) {
    lines.push(`  '${alias}': '${target}',`)
  }
  lines.push('}')
  lines.push('')

  // Installable components (exclude internal-only)
  const installable = components
    .filter(c => !INTERNAL_ONLY.has(c.name))
    .map(c => c.name)
  lines.push('/** Components available via `7onic add` (excludes internal-only) */')
  lines.push(`export const INSTALLABLE_COMPONENTS = ${JSON.stringify(installable, null, 2)} as const`)
  lines.push('')

  // Export type
  lines.push('export type ComponentName = (typeof INSTALLABLE_COMPONENTS)[number]')
  lines.push('')

  return lines.join('\n')
}

// Main
const files = fs.readdirSync(UI_DIR)
  .filter(f => f.endsWith('.tsx') && f !== 'index.ts')
  .sort()

const components = files.map(f => parseComponent(path.join(UI_DIR, f)))

const output = generateRegistryFile(components)
fs.writeFileSync(OUTPUT, output, 'utf-8')

console.log(`✅ Registry generated: ${components.length} components → ${path.relative(process.cwd(), OUTPUT)}`)

// Summary
const namespaced = components.filter(c => c.namespace).length
const withDeps = components.filter(c => c.registryDependencies.length > 0).length
const installable = components.filter(c => !INTERNAL_ONLY.has(c.name)).length

console.log(`   Namespace: ${namespaced} | Internal deps: ${withDeps} | Installable: ${installable}`)
